### ISSUE TITLE
Сервер падает при отправке длинного сообщения

### ISSUE THREAD

**Issue by iliakonnov** [stasivs/Messenger#3]
Если отправить сообщение длиной более 1024 символов (как минимум), то сервер падает с ошибкой и больше на новые сообщения от этого пользователя не реагирует
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "User.py", line 98, in receive
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by iliakonnov** [comment]
Туда же: клиент не принимает новые сообщения после отправки длинного сообщения через консоль
